#     ___    __    ___   __________  __________________  __
#    /   |  / /   /   | / ____/ __ \/  _/_  __/_  __/\ \/ /
#   / /| | / /   / /| |/ /   / /_/ // /  / /   / /    \  / 
#  / ___ |/ /___/ ___ / /___/ _, _// /  / /   / /     / /  
# /_/  |_/_____/_/  |_\____/_/ |_/___/ /_/   /_/     /_/   
#
# https://github.com/jorgeloopzz  

[cursor]
style = {shape = "Beam", blinking = "On"}

[window]
opacity = 0.9
blur = true

[window.padding]
x = 6
y = 6
